INSERT INTO "SABRH"."USUARIO" (CD_CODIGO, TX_LOGIN, IN_PERFIL, TX_SENHA, IN_STATUS) VALUES ('1', 'thiago', 'a', 'admin', 'a');
INSERT INTO "SABRH"."USUARIO" (CD_CODIGO, TX_LOGIN, IN_PERFIL, TX_SENHA, IN_STATUS) VALUES ('2', 'rony', 'a', 'admin', 'a');
